openapi: 3.0.0
info:
  title: Recruiter Information
  version: 1.0.0
  description: Add Recruiter Infomation

paths:
  /add:
    post:
      summary: add the Recruiter details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecruiterDTO'
      responses:
        '200':
          description: Successfully registered Recruiter
          content:
            application/json:
              schema:
                type: string



components:
  schemas:
    RecruiterDTO:
      type: object
      properties:
        recruiterName:
          type: string
        recruiterAge:
          type: integer

