openapi: 3.0.0
info:
  title: Admin Service API
  description: API specification for the Admin microservice.
  version: 1.0.0
paths:
  /hi:
    get:
      summary:  Hi from Admin Service
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
  /recruiter:
    get:
      tags:
        - Recruiter
      summary: Get all recruiters
      responses:
        '200':
          description: List of recruiters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecruiterDTO'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

    post:
      tags:
        - Recruiter
      summary: Add a new recruiter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecruiterDTO'
      responses:
        '201':
          description: Recruiter created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecruiterDTO'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /recruiter/{id}:
    get:
      tags:
        - Recruiter
      summary: Get recruiter by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Recruiter details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecruiterDTO'
        '400':
          description: Bad Request
        '404':
          description: Recruiter not found
        '500':
          description: Internal Server Error

    put:
      tags:
        - Recruiter
      summary: Update recruiter by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecruiterDTO'
      responses:
        '200':
          description: Recruiter updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecruiterDTO'
        '400':
          description: Bad Request
        '404':
          description: Recruiter not found
        '500':
          description: Internal Server Error

    delete:
      tags:
        - Recruiter
      summary: Delete recruiter by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Recruiter deleted successfully
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad Request
        '404':
          description: Recruiter not found
        '500':
          description: Internal Server Error

components:
  schemas:
    RecruiterDTO:
      type: object
      required:
        - name
        - designation
        - email
        - phoneNumber
        - location
        - company
      properties:
        id:
          type: string
          example: "101"
        name:
          type: string
          example: "Kavishree"
        designation:
          type: string
          example: "Senior Technical Recruiter"
        email:
          type: string
          format: email
          example: "primary@company.com"
        secondaryEmail:
          type: string
          format: email
          nullable: true
          example: "secondary@company.com"
        phoneNumber:
          type: string
          example: "+91 9876543210"
        mobileNumber:
          type: string
          nullable: true
          example: "+91 8765432109"
        location:
          type: string
          example: "Chennai, Tamil Nadu"
        company:
          type: string
          example: "Mentor Bridge"
        description:
          type: string
          example: "Recruiter with 10 years of experience in IT hiring."
        createdAt:
          type: string
        createdBy:
          type: string
        updatedAt:
          type: string
        updatedBy:
          type: string
