openapi: 3.0.0
info:
  title: Admin Service API
  description: API specification for the Admin microservice.
  version: 1.0.0
paths:
  /hi:
    get:
      summary:  Hi from Admin Service
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string

  /verify-domain/{id}:
    get:
      tags:
        - Subdomain
      summary: To check subdomain availability
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string

      responses:
        '200':
          description: Subdomain available
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Subdomain not available
          content:
            application/json:
              schema:
                type: string