openapi: 3.0.0
info:
  title: Admin API
  version: 1.0.0
  description: API for managing admin portal

paths:
  /hi:
    get:
      summary:  Hi from Admin Service
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string


  /company:
    get:
      tags:
        - Company
      summary: Get all companies
      responses:
        '200':
          description: List of companies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CompanyDTO'
        '400':
          description: Bad Request
        '500':
          description: Server Error

    post:
      tags:
        - Company
      summary: Add a new company
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyDTO'
      responses:
        '201':
          description: Company created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyDTO'
        '400':
          description: Bad Request
        '500':
          description: Server Error

  /company/{id}:
    get:
      tags:
        - Company
      summary: Get company by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Company details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyDTO'
        '400':
          description: Bad Request
        '404':
          description: Company not found
        '500':
          description: Server Error

    put:
      tags:
        - Company
      summary: Update company details by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyDTO'
      responses:
        '200':
          description: Company updated
          content:
            application/json:
              schema:

                $ref: '#/components/schemas/CompanyDTO'
        '400':
          description: Bad Request
        '404':
          description: Company not found
        '500':
          description: Server Error

    delete:
      tags:
        - Company
      summary: Delete company by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Company deleted
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad Request
        '404':
          description: Company not found
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                type: string


components:
  schemas:
    CompanyDTO:
      type: object
      required:
        - companyName
        - location
        - industry
        - website
      properties:
        id:
          type: string
          example: "1"
        companyName:
          type: string
          example: "Microsoft"
        location:
          type: string
          example: "Hyderabad, India"
        industry:
          type: string
          example: "Software"
        website:
          type: string
          format: uri
          example: "https://microsoft.com"
        specialities:
          type: string
          example: "Cloud, AI, Productivity, Tools"
        description:
          type: string
          example: "Leading technology company specializing in software and cloud solutions."
        createdAt:
          type: string
          example: "2025-09-18T00:00:00Z"
        createdBy:
          type: string
          example: "admin_user"
        updatedAt:
          type: string
          example: "2025-09-19T00:00:00Z"
        updatedBy:
          type: string
          example: "editor_user"

