openapi: 3.0.0
info:
  title: Admin Service API
  description: API specification for the Admin microservice.
  version: 1.0.0
paths:
  /hi:
    get:
      summary:  Hi from Admin Service
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
  /auth/enroll:
    post:
      summary: Stores user profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDTO"

      responses:
        "201":
          description: Successfully Registered
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDTO"

components:
  schemas:
    UserDTO:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        type:
          type: string
