openapi: 3.0.0
info:
  title: Admin Information
  version: 1.0.0
  description: Add Admin Infomation

paths:
  /add:
    post:
      summary: add the admin details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminDTO'
      responses:
        '200':
          description: Successfully registered admin
          content:
            application/json:
              schema:
                type: string



components:
  schemas:
    AdminDTO:
      type: object
      properties:
        adminName:
          type: string
        adminAge:
          type: integer

