openapi: 3.0.0
info:
  title: Admin Service API
  description: API specification for the Admin microservice.
  version: 1.0.0
paths:
  /hi:
    get:
      summary:  Hi from Admin Service
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string