openapi: 3.0.0
info:
  title: Student Service API
  description: API specification for the Student microservice.
  version: 1.0.0
paths:
  /test:
    get:
      summary:  test from Student Service
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string