openapi: 3.0.0
info:
  title: Student Information
  version: 1.0.0
  description: Add Student Infomation

paths:
  /add:
    post:
      summary: add the Student details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentDTO'
      responses:
        '200':
          description: Successfully registered Student
          content:
            application/json:
              schema:
                type: string



components:
  schemas:
    StudentDTO:
      type: object
      properties:
        studentName:
          type: string
        studentAge:
          type: integer

